# +-------------------------------------------------------+
# | Debian-based distros                                  |
# +-------------------------------------------------------+
# | Here, we run tasks to setup all debian-based distros  |
# +-------------------------------------------------------+
- include_vars: '../vars/Debian.yml'

# +-------------------------------------------------------+
# | APT                                                   |
# +-------------------------------------------------------+
- name: Add repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ apt_repos }}"
  become: true

- name: Add keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ apt_keys }}"
  become: true

- name: Update apt
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ apt_packages_base }}"
  become: true

# +-------------------------------------------------------+
# | Flatpak                                               |
# +-------------------------------------------------------+
- include_tasks: "./setup-flatpak.yml"
