- include_vars: '../vars/vim.yml'

- name: Install Vim
  package:
    name: '{{ vim_deps}}'
    state: latest
  become: true

- name: Install NeoVim
  package:
    name: '{{ neovim_deps }}'
    state: latest
  become: true

- name: Stat Vim
  stat:
    path: "{{ item }}"
  with_items:
    - '{{ home_dir }}/.vim'
    - '{{ dotfiles_dir }}/home/.vimrc'
  register: vim
