# +------------------------+
# | ZSH                    |
# +------------------------+
- name: Install ZSH deps
  package:
    state: latest
    name:
      - autoconf
      - subversion
  become: true

- name: Install ZSH
  package:
    name: zsh
    state: latest
  become: true

- name: Set ZSH as default shell
  user:
    shell: /usr/bin/zsh
    name: "{{ ansible_env.USER }}"
  become: true

# +------------------------+
# | Config                 |
# +------------------------+
# Copy over files for ZSH & Zinit
- name: Stat zinit
  stat:
    path: "{{ item }}"
  with_items:
    - '{{ home_dir }}/.zinit/bin'
    - '{{ dotfiles_dir }}/home/.zshrc'
  register: zsh

# Create default .zshrc file if one is not provided
- name: Creating new ~/.zshrc
  copy:
    src: /etc/zsh/zshrc
    dest: '{{ dotfiles_dir }}/home/.zshrc'
  when: zsh.results[1].stat.exists == False

# +------------------------+
# | Plugin Manager: zinit  |
# +------------------------+
- name: Install zinit deps
  package:
    state: latest
    name:
     - autoconf
     - libncurses5-dev
     - libncursesw5-dev
     - subversion
  become: true

# Clone Zinit plugin manager for ZSH
- name: Clone zinit
  git:
    repo: https://github.com/zdharma/zinit.git
    dest: '{{ home_dir }}/.zinit/bin'
  register: clone_zinit
  when: zsh.results[0].stat.exists == False
