- name: Install deps
  package:
    name:
      - build-essential
      - make
      - autoconf
      - automake
      - pkg-config
    state: present
  become: true

- name: Clone tmux repo
  git:
    repo: https://github.com/tmux/tmux.git
    dest: /tmp/tmux

- name: Configure & install
  command: "cd /tmp/tmux && sh autogen.sh && ./configure && make"
