# +------------------------+
# |       ZSH & ZINIT      |
# +------------------------+
- include_vars: '../vars/zsh.yml'

- name: Install zsh dependencies
  package:
    name: '{{ zsh_deps }}'
    state: 'latest'
  become: true

# Copy over files for ZSH & Zinit
- name: Stat zinit
  stat:
    path: "{{ item }}"
  with_items:
    - '{{ home_dir }}/.zinit/bin'
    - '{{ dotfiles_dir }}/home/.zshrc'
  register: zsh

# Clone Zinit plugin manager for ZSH
- name: Clone zinit
  git:
    repo=https://github.com/zdharma/zinit.git
    dest='{{ home_dir }}/.zinit/bin'
  register: clone_zinit
  when: zsh.results[0].stat.exists == False

# Create default .zshrc file if one is not provided
- name: Creating new ~/.zshrc
  copy:
    src='/etc/zsh/zshrc'
    dest='{{ dotfiles_dir }}/home/.zshrc'
  when: zsh.results[1].stat.exists == False
