# Ubuntu is a Debian-based distribution.
# We will run our Debian configuration first.
- include_tasks: 'Debian.yml'

- include_vars: '../vars/Ubuntu.yml'

- name: Add repos
  apt_repository: 
    repo: "{{ item }}" 
    state: present
  with_items: "{{ apt_repos }}"
  become: true

#- name: Add keys
#  apt_key:
#  url: "{{ item }}"
#  state: present
#with_items: "{{ apt_keys }}"
#become: true

- name: Ensure apt is updated
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install Gnome Software
  apt:
    name:
      - gnome-software
      - gnome-software-plugin-snap
      - gnome-software-plugin-flatpak
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Remove Ubuntu Software
  community.general.snap:
    name:
      - snap-store
    state: absent
  when: ansible_distribution == "Ubuntu"

- name: Set default shell to zsh
  user:
    shell: /usr/bin/zsh
    name: "{{ ansible_env.USER }}"
    # command: "chsh -s $(which zsh)"
  become: true
