- hosts: localhost
  tasks:
    - debug: msg="{{ ansible_distribution }}.yml"
    - debug: msg="{{ ansible_distribution_release }}"
    - debug: msg="{{ ansible_distribution_version }}"
    - debug: msg="{{ ansible_pkg_mgr }}"
    - name: Stat OS-specific vars and tasks
      stat:
        path: "{{ item }}"
      with_items:
        - "vars/{{ ansible_distribution }}.yml"
        - "tasks/{{ ansible_distribution }}.yml"
        - "vars/some.yml"
      register: os
    - set_fact:
        path_stat: "{{ path_stat | default([]) + [ {item.item: item.stat.exists} ] }}"
      with_items: "{{ os.results }}"
    - debug: msg="{{ path_stat }}"
    - debug: msg="{{ ansible_os_family }}"